import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import Header from "@/components/mobile/header/Header";
import TabMenu from "@/components/mobile/tab/TabMenu";
import TabProvider from "@/contexts/TabContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="light">
          {/* <ThemePanel/> */}
          <Header />
          <TabProvider>
            <TabMenu />
            {children}
          </TabProvider>
        </Theme>
      </body>
    </html>
  );
}
